### PR TITLE
add custom style to map

### PR DESCRIPTION
**Pull request by balint245**
now it is possible to add custom style to map, onMapCreated override did not affect the real onMapCreated function

### CODE REVIEW

**Comment by martin-braun** [comment]
Hi, thank you for your PR, I'm currently very busy, but I will look into it, although I cannot apply this in the current form, because it contains too many unrelated changes.

**Comment by martin-braun** [comment]
I decided that it's a better choice to expose the onMapCreated event as the lib supposed to do in the first place. This way you can simply bind to onMapCreated and apply the style yourself.

I currently have some publishing issues here at the moment. Once they are solved and the next version is published I will close this PR. Please pull the new version when it's ready.

**Comment by SzuJanLin** [comment]
thank you for making to custom style, this is exactly what i needed. Hopefully the new version onMapCreated override will affect the real onMapCreated function

**Comment by martin-braun** [comment]
@balint245 @SzuJanLin New version 2.0.0-mb.14 is up. Pull it and you can bind to `onMapCreated` yourself to apply your custom theme.

**Pull request closed without merging**
